### ISSUE TITLE
undefined method `compute_if_absent' for {}:Concurrent::Hash (NoMethodError)

### ISSUE THREAD

**Issue by mensfeld** [ruby-concurrency/concurrent-ruby#993]
With `concurrent-ruby` `1.2.0` things work as expected. With `1.2.1` I get following error:

```ruby
undefined method `compute_if_absent' for {}:Concurrent::Hash (NoMethodError)
```

relevant stacktrace:

```ruby
gems/concurrent-ruby-1.2.1/lib/concurrent-ruby/concurrent/collection/map/non_concurrent_map_backend.rb:22:in `[]'
```

it's a divination of behaviour of map, working on repro :pray: 

```ruby
# Works in 1.2.0 but breaks in 1.2.1
@listeners = Concurrent::Map.new do |h, k|
  h.compute_if_absent(k) { Concurrent::Array.new }
end

@listeners[:a]
```

**Comment by dentarg** [comment]
A regression from https://github.com/ruby-concurrency/concurrent-ruby/pull/989?

**Comment by eregon** [comment]
Sorry about this bug, I'll make a release with the fix ASAP.

**Comment by misdoro** [comment]
Same for `fetch_or_store` method on the Hash:
```
NoMethodError: undefined method `fetch_or_store' for {}:Concurrent::Hash
          h.fetch_or_store(key, Concurrent::Map.new)
```

**Comment by eregon** [comment]
Release as https://github.com/ruby-concurrency/concurrent-ruby/releases/tag/v1.2.2

**Comment by mensfeld** [comment]
Thank you for such fast turnaround!

**Comment by nijikon** [comment]
That was super quick, thanks!

**Comment by jcoyne** [comment]
Thank you for the fix. ❤️
